/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    admins: AdminAuthOperations;
  };
  blocks: {};
  collections: {
    admins: Admin;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    admins: AdminsSelect<false> | AdminsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ms') | ('en' | 'ms')[];
  globals: {
    nav: Nav;
    footer: Footer;
    home: Home;
    about: About;
    research: Research;
    resources: Resource;
    people: Person;
    blogs: Blog;
    contact: Contact;
  };
  globalsSelect: {
    nav: NavSelect<false> | NavSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    home: HomeSelect<false> | HomeSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    research: ResearchSelect<false> | ResearchSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    contact: ContactSelect<false> | ContactSelect<true>;
  };
  locale: 'en' | 'ms';
  widgets: {
    collections: CollectionsWidget;
  };
  user: Admin;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface AdminAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins".
 */
export interface Admin {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'admins';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?: {
    relationTo: 'admins';
    value: number | Admin;
  } | null;
  globalSlug?: string | null;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'admins';
    value: number | Admin;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admins_select".
 */
export interface AdminsSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav".
 */
export interface Nav {
  id: number;
  brand?: string | null;
  items?:
    | {
        key?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  tagline?: string | null;
  projectTitle?: string | null;
  connectTitle?: string | null;
  rights?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  heroTitle?: string | null;
  heroSubtitle?: string | null;
  heroPrimaryCta?: string | null;
  heroSecondaryCta?: string | null;
  missionQuote?: string | null;
  approachTitle?: string | null;
  approachSubtitle?: string | null;
  highlights?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaTitle?: string | null;
  ctaSubtitle?: string | null;
  ctaPrimary?: string | null;
  ctaSecondary?: string | null;
  communitiesTitle?: string | null;
  communitiesSubtitle?: string | null;
  communityLabel?: string | null;
  communities?: string[] | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  headerTitle?: string | null;
  headerSubtitle?: string | null;
  problemTitle?: string | null;
  problemParagraphs?: string[] | null;
  statBigNumber?: string | null;
  statBigLabel?: string | null;
  statBigSub?: string | null;
  statSmallNumber?: string | null;
  statSmallLabel?: string | null;
  statSmallSub?: string | null;
  approachTitle?: string | null;
  approachSubtitle?: string | null;
  approachItems?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  communitiesTitle?: string | null;
  communitiesSubtitle?: string | null;
  communities?:
    | {
        name?: string | null;
        subtitle?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research".
 */
export interface Research {
  id: number;
  headerTitle?: string | null;
  headerSubtitle?: string | null;
  area1Badge?: string | null;
  area1Title?: string | null;
  area1Intro?: string | null;
  area1Cards?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  area2Badge?: string | null;
  area2Title?: string | null;
  area2Intro?: string | null;
  area2Body?: string | null;
  area2Stats?:
    | {
        stat?: string | null;
        label?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  area3Badge?: string | null;
  area3Title?: string | null;
  area3Intro?: string | null;
  area3PrinciplesTitle?: string | null;
  area3Principles?:
    | {
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  headerTitle?: string | null;
  headerSubtitle?: string | null;
  dictionariesTitle?: string | null;
  dictionariesSubtitle?: string | null;
  dictionaryCardLabel?: string | null;
  dictionaryButton?: string | null;
  statusActive?: string | null;
  statusInProgress?: string | null;
  dictionaries?:
    | {
        language?: string | null;
        words?: string | null;
        status?: string | null;
        id?: string | null;
      }[]
    | null;
  corporaTitle?: string | null;
  corporaSubtitle?: string | null;
  corporaRestricted?: string | null;
  corporaButton?: string | null;
  corpora?:
    | {
        title?: string | null;
        description?: string | null;
        tags?: string[] | null;
        id?: string | null;
      }[]
    | null;
  publicationsTitle?: string | null;
  publicationsSubtitle?: string | null;
  publications?:
    | {
        title?: string | null;
        type?: string | null;
        venue?: string | null;
        status?: string | null;
        id?: string | null;
      }[]
    | null;
  toolsTitle?: string | null;
  toolsSubtitle?: string | null;
  toolsButton?: string | null;
  tools?:
    | {
        initial?: string | null;
        title?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  headerTitle?: string | null;
  headerSubtitle?: string | null;
  piTitle?: string | null;
  piSubtitle?: string | null;
  principalInvestigators?:
    | {
        name?: string | null;
        role?: string | null;
        affiliation?: string | null;
        bio?: string | null;
        id?: string | null;
      }[]
    | null;
  researchTeamTitle?: string | null;
  researchers?:
    | {
        name?: string | null;
        role?: string | null;
        focus?: string | null;
        id?: string | null;
      }[]
    | null;
  partnersTitle?: string | null;
  partnersSubtitle?: string | null;
  partnersIntro?: string | null;
  communityPartners?:
    | {
        name?: string | null;
        community?: string | null;
        role?: string | null;
        id?: string | null;
      }[]
    | null;
  collaboratorsTitle?: string | null;
  collaboratorsSubtitle?: string | null;
  collaborators?:
    | {
        name?: string | null;
        type?: string | null;
        fullName?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: number;
  headerTitle?: string | null;
  headerSubtitle?: string | null;
  readMore?: string | null;
  loadMore?: string | null;
  newsletterTitle?: string | null;
  newsletterSubtitle?: string | null;
  newsletterPlaceholder?: string | null;
  newsletterButton?: string | null;
  categories?:
    | {
        name?: string | null;
        count?: number | null;
        id?: string | null;
      }[]
    | null;
  posts?:
    | {
        postId?: number | null;
        title?: string | null;
        category?: string | null;
        date?: string | null;
        excerpt?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact".
 */
export interface Contact {
  id: number;
  headerTitle?: string | null;
  headerSubtitle?: string | null;
  infoTitle?: string | null;
  infoIntro?: string | null;
  contactInfo?:
    | {
        title?: string | null;
        details?: string[] | null;
        id?: string | null;
      }[]
    | null;
  formTitle?: string | null;
  formFirstName?: string | null;
  formLastName?: string | null;
  formEmail?: string | null;
  formSubject?: string | null;
  formSubjectPlaceholder?: string | null;
  formSubjectOptions?: string[] | null;
  formMessage?: string | null;
  formMessagePlaceholder?: string | null;
  formButton?: string | null;
  teamTitle?: string | null;
  teamSubtitle?: string | null;
  teamLocations?:
    | {
        name?: string | null;
        role?: string | null;
        location?: string | null;
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  mapTitle?: string | null;
  mapSubtitle?: string | null;
  mapPlaceholderTitle?: string | null;
  mapPlaceholderSubtitle?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "nav_select".
 */
export interface NavSelect<T extends boolean = true> {
  brand?: T;
  items?:
    | T
    | {
        key?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  tagline?: T;
  projectTitle?: T;
  connectTitle?: T;
  rights?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroTitle?: T;
  heroSubtitle?: T;
  heroPrimaryCta?: T;
  heroSecondaryCta?: T;
  missionQuote?: T;
  approachTitle?: T;
  approachSubtitle?: T;
  highlights?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  ctaTitle?: T;
  ctaSubtitle?: T;
  ctaPrimary?: T;
  ctaSecondary?: T;
  communitiesTitle?: T;
  communitiesSubtitle?: T;
  communityLabel?: T;
  communities?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  headerTitle?: T;
  headerSubtitle?: T;
  problemTitle?: T;
  problemParagraphs?: T;
  statBigNumber?: T;
  statBigLabel?: T;
  statBigSub?: T;
  statSmallNumber?: T;
  statSmallLabel?: T;
  statSmallSub?: T;
  approachTitle?: T;
  approachSubtitle?: T;
  approachItems?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  communitiesTitle?: T;
  communitiesSubtitle?: T;
  communities?:
    | T
    | {
        name?: T;
        subtitle?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research_select".
 */
export interface ResearchSelect<T extends boolean = true> {
  headerTitle?: T;
  headerSubtitle?: T;
  area1Badge?: T;
  area1Title?: T;
  area1Intro?: T;
  area1Cards?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  area2Badge?: T;
  area2Title?: T;
  area2Intro?: T;
  area2Body?: T;
  area2Stats?:
    | T
    | {
        stat?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  area3Badge?: T;
  area3Title?: T;
  area3Intro?: T;
  area3PrinciplesTitle?: T;
  area3Principles?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  headerTitle?: T;
  headerSubtitle?: T;
  dictionariesTitle?: T;
  dictionariesSubtitle?: T;
  dictionaryCardLabel?: T;
  dictionaryButton?: T;
  statusActive?: T;
  statusInProgress?: T;
  dictionaries?:
    | T
    | {
        language?: T;
        words?: T;
        status?: T;
        id?: T;
      };
  corporaTitle?: T;
  corporaSubtitle?: T;
  corporaRestricted?: T;
  corporaButton?: T;
  corpora?:
    | T
    | {
        title?: T;
        description?: T;
        tags?: T;
        id?: T;
      };
  publicationsTitle?: T;
  publicationsSubtitle?: T;
  publications?:
    | T
    | {
        title?: T;
        type?: T;
        venue?: T;
        status?: T;
        id?: T;
      };
  toolsTitle?: T;
  toolsSubtitle?: T;
  toolsButton?: T;
  tools?:
    | T
    | {
        initial?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  headerTitle?: T;
  headerSubtitle?: T;
  piTitle?: T;
  piSubtitle?: T;
  principalInvestigators?:
    | T
    | {
        name?: T;
        role?: T;
        affiliation?: T;
        bio?: T;
        id?: T;
      };
  researchTeamTitle?: T;
  researchers?:
    | T
    | {
        name?: T;
        role?: T;
        focus?: T;
        id?: T;
      };
  partnersTitle?: T;
  partnersSubtitle?: T;
  partnersIntro?: T;
  communityPartners?:
    | T
    | {
        name?: T;
        community?: T;
        role?: T;
        id?: T;
      };
  collaboratorsTitle?: T;
  collaboratorsSubtitle?: T;
  collaborators?:
    | T
    | {
        name?: T;
        type?: T;
        fullName?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  headerTitle?: T;
  headerSubtitle?: T;
  readMore?: T;
  loadMore?: T;
  newsletterTitle?: T;
  newsletterSubtitle?: T;
  newsletterPlaceholder?: T;
  newsletterButton?: T;
  categories?:
    | T
    | {
        name?: T;
        count?: T;
        id?: T;
      };
  posts?:
    | T
    | {
        postId?: T;
        title?: T;
        category?: T;
        date?: T;
        excerpt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_select".
 */
export interface ContactSelect<T extends boolean = true> {
  headerTitle?: T;
  headerSubtitle?: T;
  infoTitle?: T;
  infoIntro?: T;
  contactInfo?:
    | T
    | {
        title?: T;
        details?: T;
        id?: T;
      };
  formTitle?: T;
  formFirstName?: T;
  formLastName?: T;
  formEmail?: T;
  formSubject?: T;
  formSubjectPlaceholder?: T;
  formSubjectOptions?: T;
  formMessage?: T;
  formMessagePlaceholder?: T;
  formButton?: T;
  teamTitle?: T;
  teamSubtitle?: T;
  teamLocations?:
    | T
    | {
        name?: T;
        role?: T;
        location?: T;
        email?: T;
        id?: T;
      };
  mapTitle?: T;
  mapSubtitle?: T;
  mapPlaceholderTitle?: T;
  mapPlaceholderSubtitle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}